In [9]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [8]:
#numpy套件的ndarray型態,提供element-wise的操作
#將裡面數字都*3
import numpy as np
a=np.array([1,2,3,4,5])
print(a*3)

[ 3  6  9 12 15]


In [13]:
import numpy as np
z=np.zeros(6)
print(z)
#兩個3*4的陣列
z=np.zeros((2,3,4))
print(z)
print(np.arange(10))

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0 1 2 3 4 5 6 7 8 9]


ndarray的進階操作

In [14]:

my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])#取X=1所有資料
print(my_2d_array[:,1])#取=1的所有資料
print(my_2d_array[1,1])#取X=1且Y=1的資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [19]:
import numpy as np
a=np.zeros(10)
print(a)
print(a.ndim)#一維
b=a.reshape(2,5)
print(b.ndim)#二維

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
2
